// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lacuna.proto

package cx.corp.lacuna.server.data;

/**
 * Protobuf enum {@code DataType}
 */
public enum DataType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BUFFER = 0;</code>
   */
  BUFFER(0),
  /**
   * <code>BOOLEAN = 1;</code>
   */
  BOOLEAN(1),
  /**
   * <code>BYTE = 2;</code>
   */
  BYTE(2),
  /**
   * <code>CHAR_UTF8 = 3;</code>
   */
  CHAR_UTF8(3),
  /**
   * <code>CHAR_UTF16 = 4;</code>
   */
  CHAR_UTF16(4),
  /**
   * <code>SHORT = 5;</code>
   */
  SHORT(5),
  /**
   * <code>INT = 6;</code>
   */
  INT(6),
  /**
   * <code>FLOAT = 7;</code>
   */
  FLOAT(7),
  /**
   * <code>LONG = 8;</code>
   */
  LONG(8),
  /**
   * <code>DOUBLE = 9;</code>
   */
  DOUBLE(9),
  /**
   * <code>STRING_UTF8 = 10;</code>
   */
  STRING_UTF8(10),
  /**
   * <code>STRING_UTF16 = 11;</code>
   */
  STRING_UTF16(11),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>BUFFER = 0;</code>
   */
  public static final int BUFFER_VALUE = 0;
  /**
   * <code>BOOLEAN = 1;</code>
   */
  public static final int BOOLEAN_VALUE = 1;
  /**
   * <code>BYTE = 2;</code>
   */
  public static final int BYTE_VALUE = 2;
  /**
   * <code>CHAR_UTF8 = 3;</code>
   */
  public static final int CHAR_UTF8_VALUE = 3;
  /**
   * <code>CHAR_UTF16 = 4;</code>
   */
  public static final int CHAR_UTF16_VALUE = 4;
  /**
   * <code>SHORT = 5;</code>
   */
  public static final int SHORT_VALUE = 5;
  /**
   * <code>INT = 6;</code>
   */
  public static final int INT_VALUE = 6;
  /**
   * <code>FLOAT = 7;</code>
   */
  public static final int FLOAT_VALUE = 7;
  /**
   * <code>LONG = 8;</code>
   */
  public static final int LONG_VALUE = 8;
  /**
   * <code>DOUBLE = 9;</code>
   */
  public static final int DOUBLE_VALUE = 9;
  /**
   * <code>STRING_UTF8 = 10;</code>
   */
  public static final int STRING_UTF8_VALUE = 10;
  /**
   * <code>STRING_UTF16 = 11;</code>
   */
  public static final int STRING_UTF16_VALUE = 11;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DataType valueOf(int value) {
    return forNumber(value);
  }

  public static DataType forNumber(int value) {
    switch (value) {
      case 0: return BUFFER;
      case 1: return BOOLEAN;
      case 2: return BYTE;
      case 3: return CHAR_UTF8;
      case 4: return CHAR_UTF16;
      case 5: return SHORT;
      case 6: return INT;
      case 7: return FLOAT;
      case 8: return LONG;
      case 9: return DOUBLE;
      case 10: return STRING_UTF8;
      case 11: return STRING_UTF16;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DataType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
          public DataType findValueByNumber(int number) {
            return DataType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return cx.corp.lacuna.server.data.Lacuna.getDescriptor().getEnumTypes().get(0);
  }

  private static final DataType[] VALUES = values();

  public static DataType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DataType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:DataType)
}

