// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lacuna.proto

package cx.corp.lacuna.server.data;

public final class Lacuna {
  private Lacuna() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014lacuna.proto\032\031google/protobuf/any.prot" +
      "o\"o\n\013ReadRequest\022\013\n\003pid\030\001 \001(\005\022\037\n\014request" +
      "_type\030\002 \001(\0162\t.DataType\022\016\n\006offset\030\003 \001(\005\022\"" +
      "\n\004data\030\004 \001(\0132\024.google.protobuf.Any\"n\n\014Re" +
      "adResponse\022\033\n\006status\030\001 \001(\0162\013.StatusCode\022" +
      "\035\n\007request\030\002 \001(\0132\014.ReadRequest\022\"\n\004data\030\003" +
      " \001(\0132\024.google.protobuf.Any*\244\001\n\010DataType\022" +
      "\n\n\006BUFFER\020\000\022\013\n\007BOOLEAN\020\001\022\010\n\004BYTE\020\002\022\r\n\tCH" +
      "AR_UTF8\020\003\022\016\n\nCHAR_UTF16\020\004\022\t\n\005SHORT\020\005\022\007\n\003" +
      "INT\020\006\022\t\n\005FLOAT\020\007\022\010\n\004LONG\020\010\022\n\n\006DOUBLE\020\t\022\017",
      "\n\013STRING_UTF8\020\n\022\020\n\014STRING_UTF16\020\013*\037\n\nSta" +
      "tusCode\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001B\036\n\032cx.corp.la" +
      "cuna.server.dataP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_descriptor,
        new java.lang.String[] { "Pid", "RequestType", "Offset", "Data", });
    internal_static_ReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadResponse_descriptor,
        new java.lang.String[] { "Status", "Request", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
