// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lacuna.proto

package cx.corp.lacuna.server.data;

public interface ReadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.StatusCode status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.StatusCode status = 1;</code>
   */
  cx.corp.lacuna.server.data.StatusCode getStatus();

  /**
   * <code>.ReadRequest request = 2;</code>
   */
  boolean hasRequest();
  /**
   * <code>.ReadRequest request = 2;</code>
   */
  cx.corp.lacuna.server.data.ReadRequest getRequest();
  /**
   * <code>.ReadRequest request = 2;</code>
   */
  cx.corp.lacuna.server.data.ReadRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
