// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lacuna.proto

package cx.corp.lacuna.server.data;

public interface ReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pid = 1;</code>
   */
  int getPid();

  /**
   * <code>.DataType request_type = 2;</code>
   */
  int getRequestTypeValue();
  /**
   * <code>.DataType request_type = 2;</code>
   */
  cx.corp.lacuna.server.data.DataType getRequestType();

  /**
   * <code>int32 offset = 3;</code>
   */
  int getOffset();

  /**
   * <code>.google.protobuf.Any data = 4;</code>
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 4;</code>
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
