@startuml

package cx.corp.lacuna.core.domain {
    interface NativeProcess {
        pid : int
        owner : String
        description : String
    }
    class NativeProcessImpl
    NativeProcess <|.. NativeProcessImpl
}

package cx.corp.lacuna.core {
    interface MemoryReader {
        {abstract} read(NativeProcess, int, int) : byte[]
        {abstract} readBoolean(NativeProcess, int) : boolean
        {abstract} readByte(NativeProcess, int) : byte
        {abstract} readCharUTF8(NativeProcess, int) : char
        {abstract} readCharUTF16LE(NativeProcess, int) : char
        {abstract} readShort(NativeProcess, int) : short
        {abstract} readInt(NativeProcess, int) : int
        {abstract} readFloat(NativeProcess, int) : float
        {abstract} readLong(NativeProcess, int) : long
        {abstract} readDouble(NativeProcess, int) : double
        {abstract} readStringUTF8(NativeProcess, int, int) : String
        {abstract} readStringUTF16LE(NativeProcess, int, int) : String
    }
    interface MemoryWriter {
        {abstract} write(NativeProcess, int, byte[])
        {abstract} writeBoolean(NativeProcess, int, boolean)
        {abstract} writeByte(NativeProcess, int, byte)
        {abstract} writeCharUTF8(NativeProcess, int, char)
        {abstract} writeCharUTF16LE(NativeProcess, int, char)
        {abstract} writeShort(NativeProcess, int, short)
        {abstract} writeInt(NativeProcess, int, int)
        {abstract} writeFloat(NativeProcess, int, float)
        {abstract} writeLong(NativeProcess, int, long)
        {abstract} writeDouble(NativeProcess, int, double)
        {abstract} writeStringUTF8(NativeProcess, int, String)
        {abstract} writeStringUTF16LE(NativeProcess, int, String)
    }

    interface NativeProcessEnumerator {
        {abstract} getProcesses() : List<NativeProcess>
    }
    interface NativeProcessCollector {
        {abstract} NativeProcess collect(int)
    }
    interface PidEnumerator {
        {abstract} getPids() : List<Integer>
    }
    interface RawMemoryReader {
        {abstract} read(NativeProcess, int, int) : ByteBuffer
    }
    interface RawMemoryWriter {
        {abstract} write(NativeProcess, int, byte[])
    }
    
    class MemoryReaderImpl
    class MemoryWriterImpl
    class NativeProcessEnumeratorImpl
    
    NativeProcessEnumerator <|.. NativeProcessEnumeratorImpl
    NativeProcessEnumeratorImpl --> "1" PidEnumerator
    NativeProcessEnumeratorImpl --> "1" NativeProcessCollector
    
    MemoryReader <|.. MemoryReaderImpl
    MemoryReaderImpl --> "1" RawMemoryReader
    
    MemoryWriter <|.. MemoryWriterImpl
    MemoryWriterImpl --> "1" RawMemoryWriter
    
    ' RawMemoryReader ..> "1" NativeProcess : uses
    ' RawMemoryWriter ..> "1" NativeProcess : uses
    MemoryReader ..>  "1" NativeProcess : uses
    MemoryWriter ..>  "1" NativeProcess : uses
    NativeProcessEnumerator ..> "0..*" NativeProcess : creates
}

package cx.corp.lacuna.core.windows {

    package cx.corp.lacuna.core.windows.winapi {
        interface Advapi32 {
            {abstract} openProcessToken(...) : boolean
            {abstract} getTokenInformation(...) : boolean
            {abstract} lookupAccountSidW(...) : boolean
        }
        interface Psapi {
            {abstract} enumProcesses(...) : boolean
        }
        
        interface Kernel32 {
            {abstract} closeHandle(...) : boolean
            {abstract} openProcess(...) : int
            {abstract} queryFullProcessImageNameW(...) : boolean
            {abstract} readProcessMemory(...) : boolean
            {abstract} writeProcessMemory(...) : boolean
            {abstract} getProcessId(int) : int
        }
        interface CloseHandle {
            {abstract} closeHandle(...) : boolean
        }
        interface OpenProcess {
            {abstract} openProcess(...) : int
        }
        interface QueryFullProcessImageName {
            {abstract} queryFullProcessImageNameW(...) : boolean
        }
        interface ReadProcessMemory {
            {abstract} readProcessMemory(...) : boolean
        }
        interface WriteProcessMemory {
            {abstract} writeProcessMemory(...) : boolean
        }
        interface GetProcessId {
            {abstract} getProcessId(int) : int
        }
        note bottom: Only used in integration testing
        
        WriteProcessMemory <|.. Kernel32
        CloseHandle <|.. Kernel32
        OpenProcess <|.. Kernel32
        QueryFullProcessImageName <|.. Kernel32
        ReadProcessMemory <|.. Kernel32
        GetProcessId <|.left. Kernel32
    }
    
    interface ProcessDescriptionGetter {
        {abstract} get(ProcessHandle) : Optional<String>
    }
    interface ProcessOwnerGetter {
        {abstract} get(ProcessHandle) : Optional<String>
    }
    interface ProcessHandle <<AutoCloseable>> {
        {abstract} getNativeHandle() : int
    }
    interface ProcessOpener {
        {abstract} open(int, int) : ProcessHandle
    }
    
    class WindowsRawMemoryReader
    class WindowsRawMemoryWriter
    class WindowsNativeProcessCollector
    class WindowsPidEnumerator
    
    class WindowsProcessDescriptionGetter
    class WindowsProcessOpener
    class WindowsProcessOwnerGetter
    
    NativeProcessCollector <|.. WindowsNativeProcessCollector
     
    WindowsNativeProcessCollector --> "1" ProcessOpener
    WindowsNativeProcessCollector --> "1" ProcessOwnerGetter
    WindowsNativeProcessCollector --> "1" ProcessDescriptionGetter
    
    ProcessOpener ..> "1" ProcessHandle : creates
    ProcessOwnerGetter ..> "1" ProcessHandle : uses
    ProcessDescriptionGetter ..> "1" ProcessHandle : uses

    PidEnumerator <|.. WindowsPidEnumerator
    WindowsPidEnumerator --> "1" Psapi
    
    ProcessOpener <|.. WindowsProcessOpener
    ProcessOwnerGetter <|.. WindowsProcessOwnerGetter
    ProcessDescriptionGetter <|.. WindowsProcessDescriptionGetter
    
    WindowsProcessOpener --> "1" OpenProcess
    WindowsProcessOpener --> "1" CloseHandle

    WindowsProcessDescriptionGetter --> "1" QueryFullProcessImageName
    WindowsProcessOwnerGetter --> "1" Advapi32
    WindowsProcessOwnerGetter --> "1" CloseHandle
    
    RawMemoryReader <|.. WindowsRawMemoryReader
    WindowsRawMemoryReader --> "1" ReadProcessMemory
    WindowsRawMemoryReader --> "1" ProcessOpener
    
    RawMemoryWriter <|.. WindowsRawMemoryWriter
    WindowsRawMemoryWriter --> "1" WriteProcessMemory
    WindowsRawMemoryWriter --> "1" ProcessOpener
}

package cx.corp.lacuna.core.linux {
    interface MemoryProvider {
        {abstract} open(int) : InputOutputStream
    }
    class LinuxNativeProcessCollector
    class LinuxPidEnumerator
    class LinuxRawMemoryReader
    class LinuxRawMemoryReader #Monochrome
    note right: Upcoming
    class ProcPathFilter
    class FileMemoryProvider
    
    NativeProcessCollector <|.. LinuxNativeProcessCollector
    PidEnumerator <|.. LinuxPidEnumerator
    
    LinuxPidEnumerator *-- ProcPathFilter
    
    MemoryProvider <|.. FileMemoryProvider
    
    RawMemoryReader <|.. LinuxRawMemoryReader
    LinuxRawMemoryReader --> "1" MemoryProvider
    RawMemoryWriter <|.. LinuxRawMemoryWriter
    LinuxRawMemoryWriter --> "1" MemoryProvider
}

@enduml