@startuml

package cx.corp.lacuna.core.domain {
    class NativeProcess
}

package cx.corp.lacuna.core {
    interface MemoryReader {
        {abstract} read(NativeProcess, int, int) : byte[]
    }
    interface NativeProcessEnumerator {
        {abstract} getProcesses() : List<NativeProcess>
    }
    interface NativeProcessCollector {
        {abstract} NativeProcess collect(int)
    }
    interface PidEnumerator {
        {abstract} getPids() : List<Integer>
    }
    
    class NativeProcessEnumeratorImpl
    
    NativeProcessEnumerator <|.. NativeProcessEnumeratorImpl
    NativeProcessEnumeratorImpl --> "1" PidEnumerator
    NativeProcessEnumeratorImpl --> "1" NativeProcessCollector
    
    MemoryReader .up.>  "1" NativeProcess : uses
    NativeProcessEnumerator .up.> "0..*" NativeProcess : creates
}

package cx.corp.lacuna.core.serialization {
	interface TypeSerializers<T> {
		{abstract} find(Class<T>) : TypeSerializer<T>
		{abstract} register(Class<T>, TypeSerializer<T>) : boolean
	}
	interface TypeSerializer<T> {
		{abstract} canDeserialize(byte[]) : boolean
		{abstract} deserialize(byte[]) : T
		{abstract} serialize(T) : byte[]
	}
	
	class AbstractTypeSerializer<T>
	class Boolean8Serializer
	class Int32Serializer
	
	TypeSerializer  <|.. AbstractTypeSerializer
	AbstractTypeSerializer <|-- Boolean8Serializer
	AbstractTypeSerializer <|-- Int32Serializer
	
	TypeSerializers <|.. TypeSerializerImpl
	TypeSerializers --> "*" TypeSerializer
}

package cx.corp.lacuna.core.windows {

    package cx.corp.lacuna.core.windows.winapi {
        interface Kernel32 {
            {abstract} getProcessId(...) : int
            {abstract} openProcess(...) : int
            {abstract} queryFullProcessImageNameW(...) : boolean
            {abstract} readProcessMemory(...) : boolean
        }
        interface Advapi32 {
            {abstract} openProcessToken(...) : boolean
            {abstract} getTokenInformation(...) : boolean
            {abstract} lookupAccountSidW(...) : boolean
        }
        interface Psapi {
            {abstract} enumProcesses(...) : boolean
        }
    }
    
    interface ProcessDescriptionGetter {
        {abstract} get(ProcessHandle) : Optional<String>
    }
    interface ProcessOwnerGetter {
        {abstract} get(ProcessHandle) : Optional<String>
    }
    interface ProcessHandle <<AutoCloseable>> {
        {abstract} getNativeHandle() : int
    }
    interface ProcessOpener {
        {abstract} open(int, int) : ProcessHandle
    }
    
    class WindowsMemoryReader
    class WindowsNativeProcessCollector
    class WindowsPidEnumerator
    
    class WindowsProcessDescriptionGetter
    class WindowsProcessOpener
    class WindowsProcessOwnerGetter
    
    NativeProcessCollector <|.. WindowsNativeProcessCollector
     
    WindowsNativeProcessCollector --> "1" ProcessOpener
    WindowsNativeProcessCollector --> "1" ProcessOwnerGetter
    WindowsNativeProcessCollector --> "1" ProcessDescriptionGetter
    
    ProcessOpener ..> "1" ProcessHandle : creates
    ProcessOwnerGetter ..> "1" ProcessHandle : uses
    ProcessDescriptionGetter ..> "1" ProcessHandle : uses

    PidEnumerator <|.. WindowsPidEnumerator
    WindowsPidEnumerator --> "1" Psapi
    
    ProcessOpener <|.. WindowsProcessOpener
    ProcessOwnerGetter <|.. WindowsProcessOwnerGetter
    ProcessDescriptionGetter <|.. WindowsProcessDescriptionGetter
    
    WindowsProcessOpener --> "1" Kernel32
    WindowsProcessDescriptionGetter --> "1" Kernel32
    WindowsProcessOwnerGetter --> "1" Advapi32
    
    MemoryReader <|.. WindowsMemoryReader
    WindowsMemoryReader --> "1" Kernel32
	WindowsMemoryReader --> "1" ProcessOpener
}

package cx.corp.lacuna.core.linux {
    interface MemoryProvider {
        {abstract} open(int) : InputStream
    }
    class LinuxNativeProcessCollector
    class LinuxPidEnumerator
    class LinuxMemoryReader
    class ProcPathFilter
    class FileMemoryProvider
    
    NativeProcessCollector <|.. LinuxNativeProcessCollector
    PidEnumerator <|.. LinuxPidEnumerator
    
    LinuxPidEnumerator *-- ProcPathFilter
    
    MemoryProvider <|.. FileMemoryProvider
    
    MemoryReader <|.. LinuxMemoryReader
    LinuxMemoryReader --> "1" MemoryProvider
}

@enduml
